// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl2VtZoBhlZkO7cNWK0vppKS8KKU-hWtk',
    appId: '1:1257936207:ios:38437f4e07299a155ba13a',
    messagingSenderId: '1257936207',
    projectId: 'multi-ball-tracker',
    storageBucket: 'multi-ball-tracker.firebasestorage.app',
    iosBundleId: 'com.example.ballTracker.RunnerTests',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrAEfoYC6gc4qG87nayDsX5HgI_WZizSc',
    appId: '1:1257936207:web:885d39fb78f1ce455ba13a',
    messagingSenderId: '1257936207',
    projectId: 'multi-ball-tracker',
    authDomain: 'multi-ball-tracker.firebaseapp.com',
    storageBucket: 'multi-ball-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl2VtZoBhlZkO7cNWK0vppKS8KKU-hWtk',
    appId: '1:1257936207:ios:20f2167c10ef862d5ba13a',
    messagingSenderId: '1257936207',
    projectId: 'multi-ball-tracker',
    storageBucket: 'multi-ball-tracker.firebasestorage.app',
    iosBundleId: 'com.example.ballTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSXgX9fWJijQd5q8eW8eve4E4gxXappNE',
    appId: '1:1257936207:android:838af21904468e775ba13a',
    messagingSenderId: '1257936207',
    projectId: 'multi-ball-tracker',
    storageBucket: 'multi-ball-tracker.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrAEfoYC6gc4qG87nayDsX5HgI_WZizSc',
    appId: '1:1257936207:web:6a0ce3e45023c6455ba13a',
    messagingSenderId: '1257936207',
    projectId: 'multi-ball-tracker',
    authDomain: 'multi-ball-tracker.firebaseapp.com',
    storageBucket: 'multi-ball-tracker.firebasestorage.app',
  );

}