import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

// --- NEW IMPORTS ---
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

// --- MODIFIED MODEL ---
class LevelResult {
  final int level;
  final double time;
  final bool wasCompleted;
  final Timestamp timestamp; // For sorting by time

  LevelResult({
    required this.level,
    required this.time,
    required this.wasCompleted,
    required this.timestamp,
  });

  // toJson now includes the timestamp
  Map<String, dynamic> toJson() => {
    'level': level,
    'time': time,
    'wasCompleted': wasCompleted,
    'timestamp': timestamp,
  };

  // fromJson now expects a Firestore Timestamp
  factory LevelResult.fromJson(Map<String, dynamic> json) {
    return LevelResult(
      level: json['level'],
      time: json['time'],
      wasCompleted: json['wasCompleted'],
      timestamp: json['timestamp'] as Timestamp, // Read as Timestamp
    );
  }
}

// // --- MODIFIED main() ---
// Future<void> main() async {
//   // Ensure Flutter is initialized
//   WidgetsFlutterBinding.ensureInitialized();
//   // Initialize Firebase
//   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
//   runApp(const BallTrackerApp());
// }
// --- MODIFIED main() ---
void main() {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Run the app. The app itself will now handle Firebase initialization.
  runApp(BallTrackerApp());
}

// --- MODIFIED BallTrackerApp ---
class BallTrackerApp extends StatelessWidget {
  BallTrackerApp({super.key}); // <-- Removed 'const'

  final Future<FirebaseApp> _initialization = Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ball Tracking Game',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: const Color(0xFFF0F2F5),
        fontFamily: 'Roboto',
      ),
      // Use a FutureBuilder to wait for Firebase to initialize
      home: FutureBuilder(
        future: _initialization,
        builder: (context, snapshot) {
          // If there's an error (e.g., no internet, bad config)
          if (snapshot.hasError) {
            return Scaffold(
              body: Center(
                child: Text('Error initializing Firebase: ${snapshot.error}'),
              ),
            );
          }

          // If Firebase has initialized successfully, show your auth logic
          if (snapshot.connectionState == ConnectionState.done) {
            // This is YOUR existing StreamBuilder logic
            return StreamBuilder<User?>(
              stream: FirebaseAuth.instance.authStateChanges(),
              builder: (context, authSnapshot) {
                // This is the spinner for *auth*, not Firebase init
                if (authSnapshot.connectionState == ConnectionState.waiting) {
                  return const Scaffold(
                    body: Center(child: CircularProgressIndicator()),
                  );
                }

                // User is logged in
                if (authSnapshot.hasData) {
                  return GameScreen(userId: authSnapshot.data!.uid);
                }

                // User is logged out
                return const AuthScreen();
              },
            );
          }

          // While Firebase is initializing, show a loading spinner.
          // This FIXES the blank screen.
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        },
      ),
    );
  }
}

// --- MODIFIED BallTrackerApp ---
// This widget is now a "splash screen" or "auth router".
// It listens to auth state changes and shows the correct screen.
//---------------------------------------------------------------------------------------------------------------
// class BallTrackerApp extends StatelessWidget {
//   const BallTrackerApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Ball Tracking Game',
//       theme: ThemeData(
//         primarySwatch: Colors.blue,
//         scaffoldBackgroundColor: const Color(0xFFF0F2F5),
//         fontFamily: 'Roboto',
//       ),
//       home: StreamBuilder<User?>(
//         // Listen to Firebase's auth state
//         stream: FirebaseAuth.instance.authStateChanges(),
//         builder: (context, snapshot) {
//           // Show a loading spinner while checking auth state
//           if (snapshot.connectionState == ConnectionState.waiting) {
//             return const Scaffold(
//               body: Center(child: CircularProgressIndicator()),
//             );
//           }

//           // If the snapshot has data, a user is logged in.
//           if (snapshot.hasData) {
//             // User is logged in, show the GameScreen.
//             // We pass the user's unique ID (uid) from Firebase.
//             return GameScreen(userId: snapshot.data!.uid);
//           }

//           // If no data, user is logged out. Show the AuthScreen.
//           return const AuthScreen();
//         },
//       ),
//     );
//   }
// }
//---------------------------------------------------------------------------------------------------------------

// --- MODIFIED AuthScreen ---
// This screen now uses Firebase Auth for Email/Password.
class AuthScreen extends StatefulWidget {
  const AuthScreen({super.key});

  @override
  State<AuthScreen> createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  String? _errorMessage;
  bool _isLoading = false;

  // We no longer navigate from here. The StreamBuilder in BallTrackerApp
  // // handles navigation automatically when the auth state changes.
  Future<void> _login() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
        email: _emailController.text.trim(),
        password: _passwordController.text.trim(),
      );
      // No navigation needed. StreamBuilder will detect the new state.
    } on FirebaseAuthException catch (e) {
      String message;
      // Handle specific error codes
      switch (e.code) {
        case 'user-not-found':
          message = 'No user found for that email. Please sign up.';
          break;
        case 'wrong-password':
          message = 'Wrong password. Please try again.';
          break;
        case 'invalid-email':
          message = 'The email address is not valid.';
          break;
        case 'invalid-credential':
          message =
              'Invalid credentials. Please check your email and password.';
          break;
        default:
          message = e.message ?? 'An unknown error occurred.';
      }
      setState(() {
        _errorMessage = message;
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _errorMessage = "An unknown error occurred.";
        _isLoading = false;
      });
    }
  }

  Future<void> _signup() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      final email = _emailController.text.trim();
      final password = _passwordController.text.trim();

      // 1. Create the user in Firebase Auth
      final userCredential = await FirebaseAuth.instance
          .createUserWithEmailAndPassword(
            email: email, // Use the variable
            password: password, // Use the variable
          );

      if (userCredential.user == null) {
        throw Exception("User creation failed.");
      }

      final userId = userCredential.user!.uid;
      final username = email.split('@').first;
      // 2. Create a user document in Firestore to store their data
      await FirebaseFirestore.instance.collection('users').doc(userId).set({
        'email': _emailController.text.trim(),
        'displayName': username,
        'personalBest': 1, // Initialize personal best
        'createdAt': FieldValue.serverTimestamp(),
      });

      // No navigation needed. StreamBuilder will detect the new state.
    } on FirebaseAuthException catch (e) {
      String message;
      // Handle specific error codes
      switch (e.code) {
        case 'weak-password':
          message = 'The password must be at least 6 characters long.';
          break;
        case 'email-already-in-use':
          message = 'An account already exists for that email. Please log in.';
          break;
        case 'invalid-email':
          message = 'The email address is not valid.';
          break;
        default:
          message = e.message ?? 'An unknown error occurred.';
      }
      setState(() {
        _errorMessage = message;
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _errorMessage = "An unknown error occurred: $e";
        _isLoading = false;
      });
    }
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 350),
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  'Welcome to the Tracker 🧠',
                  style: Theme.of(context).textTheme.headlineSmall,
                ),
                const SizedBox(height: 24),
                TextField(
                  controller: _emailController,
                  decoration: const InputDecoration(
                    labelText: 'Email',
                    hintText: "e.g., user@example.com",
                    border: OutlineInputBorder(),
                  ),
                  keyboardType: TextInputType.emailAddress,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: _passwordController,
                  decoration: InputDecoration(
                    labelText: 'Password',
                    border: const OutlineInputBorder(),
                    errorText: _errorMessage,
                  ),
                  obscureText: true,
                ),
                const SizedBox(height: 16),
                if (_isLoading)
                  const CircularProgressIndicator()
                else
                  Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      ElevatedButton(
                        onPressed: _login,
                        style: ElevatedButton.styleFrom(
                          minimumSize: const Size(double.infinity, 40),
                        ),
                        child: const Text('Log In'),
                      ),
                      const SizedBox(height: 8),
                      OutlinedButton(
                        onPressed: _signup,
                        style: OutlinedButton.styleFrom(
                          minimumSize: const Size(double.infinity, 40),
                        ),
                        child: const Text('Sign Up'),
                      ),
                    ],
                  ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// (Ball class remains exactly the same)
class Ball {
  Offset position;
  Offset velocity;
  final double radius;
  Color color;
  final Color originalColor;
  bool isTarget;

  Ball({
    required this.position,
    required this.velocity,
    required this.color,
    this.radius = 15.0,
    this.isTarget = false,
  }) : originalColor = color;

  void draw(Canvas canvas) {
    final paint = Paint()..color = color;
    canvas.drawCircle(position, radius, paint);
  }

  void update(Size bounds) {
    if (position.dx + radius >= bounds.width || position.dx - radius <= 0) {
      velocity = Offset(-velocity.dx, velocity.dy);
    }
    if (position.dy + radius >= bounds.height || position.dy - radius <= 0) {
      velocity = Offset(velocity.dx, -velocity.dy);
    }
    position += velocity;
  }
}

// --- MODIFIED GameScreen ---
class GameScreen extends StatefulWidget {
  // We now receive the unique Firebase User ID
  final String userId;

  const GameScreen({super.key, required this.userId});

  @override
  State<GameScreen> createState() => _GameScreenState();
}

class _GameScreenState extends State<GameScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  // This holds our user's data from Firestore
  late DocumentReference _userDocRef;
  List<LevelResult> _userHistory = [];
  String _displayName = "Loading..."; // Default text while loading

  // (All game state variables remain the same)
  List<Ball> balls = [];
  bool isAnimating = false;
  bool isAwaitingClick = false;
  bool isButtonDisabled = false;
  String buttonText = "Start Level";
  String instructions = "Click 'Start' to begin. Watch the yellow balls.";
  final Size gameCanvasSize = const Size(350, 450);
  int level = 1;
  int totalBalls = 3;
  int ballsToTrack = 1;
  double speed = 2.0;
  int foundTargets = 0;
  int _personalBest = 1;
  final Stopwatch _trackingStopwatch = Stopwatch();
  final Stopwatch _reactionStopwatch = Stopwatch();
  Duration? _trackedDuration;

  static const Color targetColor = Color(0xFFFFC107);
  static const Color defaultColor = Color(0xFF007BFF);
  static const Color correctColor = Color(0xFF28A745);
  static const Color incorrectColor = Color(0xFFDC3545);

  @override
  void initState() {
    super.initState();
    _controller =
        AnimationController(vsync: this, duration: const Duration(seconds: 1))
          ..addListener(() {
            if (isAnimating) {
              setState(() {
                for (var ball in balls) {
                  ball.update(gameCanvasSize);
                }
              });
            }
          });

    // Set the reference to this user's document in Firestore
    _userDocRef = FirebaseFirestore.instance
        .collection('users')
        .doc(widget.userId);

    _loadUserData();
  }

  // --- NEW: Sign Out Method ---
  Future<void> _signOut() async {
    await FirebaseAuth.instance.signOut();
    // No navigation needed. The StreamBuilder in BallTrackerApp will handle it.
  }

  // --- MODIFIED: Loads from Firestore ---
  Future<void> _loadUserData() async {
    try {
      // 1. Load the user's main document
      final userSnapshot = await _userDocRef.get();

      if (!userSnapshot.exists) {
        // This shouldn't happen if sign-up is correct, but good to check
        await _userDocRef.set({'personalBest': 1});
      }

      final userData = userSnapshot.data() as Map<String, dynamic>?;

      // 2. Load the user's history from the subcollection
      final historySnapshot = await _userDocRef
          .collection('history')
          .orderBy('timestamp', descending: true) // Get most recent first
          .get();

      final history = historySnapshot.docs
          .map((doc) => LevelResult.fromJson(doc.data()))
          .toList();

      setState(() {
        _personalBest = userData?['personalBest'] ?? 1;
        _userHistory = history;
      });
    } catch (e) {
      // Handle error (e.g., show a snackbar)
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Error loading user data: $e")));
    }
  }

  // --- MODIFIED: Saves to Firestore Subcollection ---
  Future<void> _saveUserHistory(LevelResult result) async {
    try {
      // We add the new result to the 'history' subcollection
      // We use the model's toJson() method, which now includes the timestamp
      await _userDocRef.collection('history').add(result.toJson());

      // Add to local list to update UI immediately
      setState(() {
        _userHistory.insert(
          0,
          result,
        ); // Add to beginning (since we sort descending)
      });
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Error saving history: $e")));
    }
  }

  // --- MODIFIED: Saves to Firestore Document ---
  Future<void> _savePersonalBest() async {
    if (level > _personalBest) {
      try {
        // Update the 'personalBest' field in the user's document
        await _userDocRef.update({'personalBest': level});
        setState(() {
          _personalBest = level;
        });
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error saving personal best: $e")),
        );
      }
    }
  }

  // --- MODIFIED: Uses Firestore data ---
  Future<void> _exportHistoryToCsv() async {
    if (_userHistory.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text("No history to export.")));
      return;
    }

    final List<String> rowHeader = ['Level', 'Result', 'Time (s)', 'Timestamp'];
    List<List<String>> rows = [];
    rows.add(rowHeader);

    // _userHistory is already loaded from Firestore
    for (final result in _userHistory) {
      final List<String> row = [
        result.level.toString(),
        result.wasCompleted ? 'Answered' : 'Gave Up',
        result.time.toStringAsFixed(2),
        result.timestamp.toDate().toIso8601String(), // Add timestamp
      ];
      rows.add(row);
    }

    String csvData = rows.map((row) => row.join(',')).join('\n');

    final directory = await getTemporaryDirectory();
    // Use the Firebase UID for a unique filename
    final path = '${directory.path}/tracking_history_${widget.userId}.csv';
    final file = File(path);
    await file.writeAsString(csvData);

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text("CSV file created. Opening share dialog...")),
    );

    await Share.shareXFiles([
      XFile(path),
    ], subject: 'Ball Tracking History for User ${widget.userId}');
  }

  // (Game logic methods: _setupLevel, _startAnimation, _handleTap,
  // _handleSpaceBarPress, _increaseDifficulty, _resetLevel, _revealTargets
  // are almost identical, just the _saveUserHistory call is modified)

  // ... (setup, startAnimation, etc. are the same) ...

  void _setupLevel() {
    setState(() {
      instructions = "Watch the ${ballsToTrack} yellow ball(s).";
      isButtonDisabled = true;
      isAwaitingClick = false;
      isAnimating = false;
      foundTargets = 0;
      _trackedDuration = null;
      _reactionStopwatch.reset();
      balls.clear();

      final random = Random();
      for (int i = 0; i < totalBalls; i++) {
        const radius = 15.0;
        final x =
            radius + random.nextDouble() * (gameCanvasSize.width - 2 * radius);
        final y =
            radius + random.nextDouble() * (gameCanvasSize.height - 2 * radius);
        final angle = random.nextDouble() * 2 * pi;
        final dx = cos(angle) * speed;
        final dy = sin(angle) * speed;
        final isTarget = i < ballsToTrack;
        final color = isTarget ? targetColor : defaultColor;

        balls.add(
          Ball(
            position: Offset(x, y),
            velocity: Offset(dx, dy),
            color: color,
            isTarget: isTarget,
          ),
        );
      }
    });

    Future.delayed(const Duration(milliseconds: 2500), () {
      if (!mounted) return;
      setState(() {
        for (var ball in balls) {
          ball.color = defaultColor;
        }
        instructions = 'Tracking... (Press SPACE if you lose track)';
      });
      _startAnimation();
    });
  }

  void _startAnimation() {
    isAnimating = true;
    _trackingStopwatch.reset();
    _trackingStopwatch.start();
    _controller.repeat();

    Future.delayed(const Duration(seconds: 6), () {
      if (!isAnimating || !mounted) return;
      _trackingStopwatch.stop();
      isAnimating = false;
      _controller.stop();

      _reactionStopwatch.reset();
      _reactionStopwatch.start();

      setState(() {
        isAwaitingClick = true;
        instructions =
            "Click the ${ballsToTrack - foundTargets} ball(s) you were tracking.";
      });
    });
  }

  void _handleTap(Offset tapPosition) {
    if (!isAwaitingClick) return;
    for (final ball in balls) {
      final distance = (tapPosition - ball.position).distance;
      if (distance < ball.radius) {
        if (ball.color == correctColor || ball.color == incorrectColor)
          continue;
        setState(() {
          if (ball.isTarget) {
            ball.color = correctColor;
            foundTargets++;
            if (foundTargets == ballsToTrack) {
              _reactionStopwatch.stop();
              double reactionTimeInSeconds =
                  _reactionStopwatch.elapsedMilliseconds / 1000.0;

              instructions = "Correct! Well done! 🎉";
              isAwaitingClick = false;
              isButtonDisabled = false;
              buttonText = "Next Level";

              final result = LevelResult(
                level: level,
                time: reactionTimeInSeconds,
                wasCompleted: true,
                timestamp: Timestamp.now(), // Use current time
              );
              // --- MODIFIED CALL ---
              _saveUserHistory(result); // Pass result to save method
              _increaseDifficulty();
            } else {
              instructions =
                  "Good job! Find the remaining ${ballsToTrack - foundTargets} ball(s).";
            }
          } else {
            ball.color = incorrectColor;
            instructions = "Incorrect. Try this level again. 🤔";
            isAwaitingClick = false;
            _reactionStopwatch.stop();
            _revealTargets();
            _resetLevel();
          }
        });
        break;
      }
    }
  }

  void _handleSpaceBarPress() {
    if (!isAnimating) return;
    _trackingStopwatch.stop();
    _controller.stop();
    isAnimating = false;
    isAwaitingClick = false;

    setState(() {
      _trackedDuration = _trackingStopwatch.elapsed;
      double timeInSeconds = _trackedDuration!.inMilliseconds / 1000.0;

      final result = LevelResult(
        level: level,
        time: timeInSeconds,
        wasCompleted: false,
        timestamp: Timestamp.now(), // Use current time
      );
      // --- MODIFIED CALL ---
      _saveUserHistory(result); // Pass result to save method

      String formattedTime = timeInSeconds.toStringAsFixed(1);
      instructions = 'Tracked for ${formattedTime}s. Let\'s see the answer.';
      _revealTargets();
      _resetLevel();
    });
  }

  void _increaseDifficulty() {
    level++;
    _savePersonalBest(); // This will save to Firestore
    if (level % 2 == 0 && ballsToTrack < 5) {
      ballsToTrack++;
    }
    totalBalls++;
    if (level % 3 == 0) {
      speed += 0.25;
    }
  }

  void _resetLevel() {
    setState(() {
      isButtonDisabled = false;
      buttonText = "Try Again";
    });
  }

  void _revealTargets() {
    setState(() {
      for (final ball in balls) {
        if (ball.isTarget) {
          ball.color = targetColor;
        }
      }
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Focus(
      autofocus: true,
      onKeyEvent: (node, event) {
        if (event is KeyDownEvent &&
            event.logicalKey == LogicalKeyboardKey.space) {
          _handleSpaceBarPress();
          return KeyEventResult.handled;
        }
        return KeyEventResult.ignored;
      },
      child: Scaffold(
        // --- NEW: AppBar with Sign Out Button ---
        appBar: AppBar(
          title: Text(
            'Ball Tracker 🧠 (User: ${widget.userId.substring(0, 6)}...)',
          ),
          backgroundColor: Colors.white,
          elevation: 1,
          actions: [
            IconButton(
              icon: const Icon(Icons.logout),
              tooltip: 'Sign Out',
              onPressed: _signOut,
            ),
          ],
        ),
        body: Center(
          child: SingleChildScrollView(
            child: Container(
              padding: const EdgeInsets.all(24.0),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  // --- Title is now in the AppBar ---
                  // const SizedBox(height: 20),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Level: $level',
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      Text(
                        'Personal Best: $_personalBest',
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                          color: Colors.black54,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 10),
                  Text(
                    "Level History",
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      color: Colors.grey.shade700,
                    ),
                  ),
                  Container(
                    height: 100,
                    margin: const EdgeInsets.symmetric(vertical: 8),
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey.shade300),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: ListView.builder(
                      // Use the local _userHistory list, which is loaded from Firestore
                      itemCount: _userHistory.length,
                      itemBuilder: (context, index) {
                        final result = _userHistory[index]; // Already sorted
                        final String resultText = result.wasCompleted
                            ? "Answered in ${result.time.toStringAsFixed(1)}s"
                            : "Gave up at ${result.time.toStringAsFixed(1)}s";

                        return Padding(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 8.0,
                            vertical: 2.0,
                          ),
                          child: Text(
                            'Level ${result.level}: $resultText',
                            style: TextStyle(
                              color: result.wasCompleted
                                  ? Colors.green.shade700
                                  : Colors.red.shade700,
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8.0),
                    child: Text(
                      instructions,
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.bold,
                        color:
                            instructions.contains("Incorrect") ||
                                instructions.contains("Tracked for")
                            ? Colors.red
                            : const Color.fromARGB(255, 34, 34, 34),
                      ),
                    ),
                  ),
                  GestureDetector(
                    onTapDown: (details) => _handleTap(details.localPosition),
                    child: Container(
                      width: gameCanvasSize.width,
                      height: gameCanvasSize.height,
                      decoration: BoxDecoration(
                        border: Border.all(
                          color: Colors.grey.shade300,
                          width: 2,
                        ),
                        borderRadius: BorderRadius.circular(8.0),
                        color: const Color(0xFFF8F9FA),
                      ),
                      child: CustomPaint(
                        painter: BallPainter(balls: balls),
                        size: gameCanvasSize,
                      ),
                    ),
                  ),
                  const SizedBox(height: 20),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      ElevatedButton(
                        onPressed: isButtonDisabled ? null : _setupLevel,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF007BFF),
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(
                            horizontal: 25,
                            vertical: 12,
                          ),
                          textStyle: const TextStyle(fontSize: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(6.0),
                          ),
                        ),
                        child: Text(buttonText),
                      ),
                      const SizedBox(width: 10),
                      ElevatedButton.icon(
                        icon: const Icon(Icons.download),
                        label: const Text("Export CSV"),
                        onPressed: _exportHistoryToCsv,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.teal,
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(
                            horizontal: 25,
                            vertical: 12,
                          ),
                          textStyle: const TextStyle(fontSize: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(6.0),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// (BallPainter class remains exactly the same)
class BallPainter extends CustomPainter {
  final List<Ball> balls;
  BallPainter({required this.balls});

  @override
  void paint(Canvas canvas, Size size) {
    for (var ball in balls) {
      ball.draw(canvas);
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}
