import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

// --- NEW IMPORTS ---
// You will need to add these to your pubspec.yaml
// flutter pub add http
// flutter pub add flutter_markdown
import 'package:http/http.dart' as http;
import 'package:flutter_markdown/flutter_markdown.dart';
// --- END NEW IMPORTS ---

// --- MODIFIED MODEL ---
class LevelResult {
  final int level;
  final double time; // Time in seconds (either tracking or reaction)
  final bool wasCompleted; // True if all targets were found
  final Timestamp timestamp; // For sorting by time

  // --- NEW FIELDS ---
  final bool gaveUp; // True if spacebar was pressed
  final bool wasIncorrect; // True if the wrong ball was clicked
  final int targetsInLevel; // How many targets they had to track
  final int targetsFound; // How many they found before failing/succeeding

  LevelResult({
    required this.level,
    required this.time,
    required this.wasCompleted,
    required this.timestamp,
    // --- NEW ---
    required this.gaveUp,
    required this.wasIncorrect,
    required this.targetsInLevel,
    required this.targetsFound,
  });

  // toJson now includes the new fields
  Map<String, dynamic> toJson() => {
    'level': level,
    'time': time,
    'wasCompleted': wasCompleted,
    'timestamp': timestamp,
    // --- NEW ---
    'gaveUp': gaveUp,
    'wasIncorrect': wasIncorrect,
    'targetsInLevel': targetsInLevel,
    'targetsFound': targetsFound,
  };

  // fromJson now expects the new fields
  // Added fallbacks (??) for backward compatibility with your old data
  factory LevelResult.fromJson(Map<String, dynamic> json) {
    return LevelResult(
      level: json['level'],
      time: json['time'],
      wasCompleted: json['wasCompleted'],
      timestamp: json['timestamp'] as Timestamp,
      // --- NEW ---
      gaveUp: json['gaveUp'] ?? false,
      wasIncorrect: json['wasIncorrect'] ?? false,
      targetsInLevel: json['targetsInLevel'] ?? 0,
      targetsFound: json['targetsFound'] ?? 0,
    );
  }
}

// --- MODIFIED main() ---
void main() {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Run the app. The app itself will now handle Firebase initialization.
  runApp(BallTrackerApp());
}

// --- MODIFIED BallTrackerApp ---
class BallTrackerApp extends StatelessWidget {
  BallTrackerApp({super.key}); // <-- Removed 'const'

  final Future<FirebaseApp> _initialization = Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Ball Tracking Game',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        scaffoldBackgroundColor: const Color(0xFFF0F2F5),
        fontFamily: 'Roboto',
      ),
      // Use a FutureBuilder to wait for Firebase to initialize
      home: FutureBuilder(
        future: _initialization,
        builder: (context, snapshot) {
          // If there's an error (e.g., no internet, bad config)
          if (snapshot.hasError) {
            return Scaffold(
              body: Center(
                child: Text('Error initializing Firebase: ${snapshot.error}'),
              ),
            );
          }

          // If Firebase has initialized successfully, show your auth logic
          if (snapshot.connectionState == ConnectionState.done) {
            // This is YOUR existing StreamBuilder logic
            return StreamBuilder<User?>(
              stream: FirebaseAuth.instance.authStateChanges(),
              builder: (context, authSnapshot) {
                // This is the spinner for *auth*, not Firebase init
                if (authSnapshot.connectionState == ConnectionState.waiting) {
                  return const Scaffold(
                    body: Center(child: CircularProgressIndicator()),
                  );
                }

                // User is logged in
                if (authSnapshot.hasData) {
                  return GameScreen(userId: authSnapshot.data!.uid);
                }

                // User is logged out
                return const AuthScreen();
              },
            );
          }

          // While Firebase is initializing, show a loading spinner.
          // This FIXES the blank screen.
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        },
      ),
    );
  }
}

// (AuthScreen remains the same)
// --- MODIFIED AuthScreen ---
// This screen now uses Firebase Auth for Email/Password.
class AuthScreen extends StatefulWidget {
  const AuthScreen({super.key});

  @override
  State<AuthScreen> createState() => _AuthScreenState();
}

class _AuthScreenState extends State<AuthScreen> {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  String? _errorMessage;
  bool _isLoading = false;

  // We no longer navigate from here. The StreamBuilder in BallTrackerApp
  // // handles navigation automatically when the auth state changes.
  Future<void> _login() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
        email: _emailController.text.trim(),
        password: _passwordController.text.trim(),
      );
      // No navigation needed. StreamBuilder will detect the new state.
    } on FirebaseAuthException catch (e) {
      String message;
      // Handle specific error codes
      switch (e.code) {
        case 'user-not-found':
          message = 'No user found for that email. Please sign up.';
          break;
        case 'wrong-password':
          message = 'Wrong password. Please try again.';
          break;
        case 'invalid-email':
          message = 'The email address is not valid.';
          break;
        case 'invalid-credential':
          message =
              'Invalid credentials. Please check your email and password.';
          break;
        default:
          message = e.message ?? 'An unknown error occurred.';
      }
      setState(() {
        _errorMessage = message;
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _errorMessage = "An unknown error occurred.";
        _isLoading = false;
      });
    }
  }

  Future<void> _signup() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      final email = _emailController.text.trim();
      final password = _passwordController.text.trim();

      // 1. Create the user in Firebase Auth
      final userCredential = await FirebaseAuth.instance
          .createUserWithEmailAndPassword(
            email: email, // Use the variable
            password: password, // Use the variable
          );

      if (userCredential.user == null) {
        throw Exception("User creation failed.");
      }

      final userId = userCredential.user!.uid;
      final username = email.split('@').first;
      // 2. Create a user document in Firestore to store their data
      await FirebaseFirestore.instance.collection('users').doc(userId).set({
        'email': _emailController.text.trim(),
        'displayName': username,
        'personalBest': 1, // Initialize personal best
        'createdAt': FieldValue.serverTimestamp(),
      });

      // No navigation needed. StreamBuilder will detect the new state.
    } on FirebaseAuthException catch (e) {
      String message;
      // Handle specific error codes
      switch (e.code) {
        case 'weak-password':
          message = 'The password must be at least 6 characters long.';
          break;
        case 'email-already-in-use':
          message = 'An account already exists for that email. Please log in.';
          break;
        case 'invalid-email':
          message = 'The email address is not valid.';
          break;
        default:
          message = e.message ?? 'An unknown error occurred.';
      }
      setState(() {
        _errorMessage = message;
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _errorMessage = "An unknown error occurred: $e";
        _isLoading = false;
      });
    }
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 350),
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(
                  'Welcome to the Tracker 🧠',
                  style: Theme.of(context).textTheme.headlineSmall,
                ),
                const SizedBox(height: 24),
                TextField(
                  controller: _emailController,
                  decoration: const InputDecoration(
                    labelText: 'Email',
                    hintText: "e.g., user@example.com",
                    border: OutlineInputBorder(),
                  ),
                  keyboardType: TextInputType.emailAddress,
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: _passwordController,
                  decoration: InputDecoration(
                    labelText: 'Password',
                    border: const OutlineInputBorder(),
                    errorText: _errorMessage,
                  ),
                  obscureText: true,
                ),
                const SizedBox(height: 16),
                if (_isLoading)
                  const CircularProgressIndicator()
                else
                  Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      ElevatedButton(
                        onPressed: _login,
                        style: ElevatedButton.styleFrom(
                          minimumSize: const Size(double.infinity, 40),
                        ),
                        child: const Text('Log In'),
                      ),
                      const SizedBox(height: 8),
                      OutlinedButton(
                        onPressed: _signup,
                        style: OutlinedButton.styleFrom(
                          minimumSize: const Size(double.infinity, 40),
                        ),
                        child: const Text('Sign Up'),
                      ),
                    ],
                  ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// (Ball class remains exactly the same)
class Ball {
  Offset position;
  Offset velocity;
  final double radius;
  Color color;
  final Color originalColor;
  bool isTarget;

  Ball({
    required this.position,
    required this.velocity,
    required this.color,
    this.radius = 15.0,
    this.isTarget = false,
  }) : originalColor = color;

  void draw(Canvas canvas) {
    final paint = Paint()..color = color;
    canvas.drawCircle(position, radius, paint);
  }

  void update(Size bounds) {
    if (position.dx + radius >= bounds.width || position.dx - radius <= 0) {
      velocity = Offset(-velocity.dx, velocity.dy);
    }
    if (position.dy + radius >= bounds.height || position.dy - radius <= 0) {
      velocity = Offset(velocity.dx, -velocity.dy);
    }
    position += velocity;
  }
}

// --- MODIFIED GameScreen ---
class GameScreen extends StatefulWidget {
  // We now receive the unique Firebase User ID
  final String userId;

  const GameScreen({super.key, required this.userId});

  @override
  State<GameScreen> createState() => _GameScreenState();
}

class _GameScreenState extends State<GameScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;

  // This holds our user's data from Firestore
  late DocumentReference _userDocRef;
  List<LevelResult> _userHistory = [];
  String _displayName = "Loading..."; // Default text while loading

  // (All game state variables remain the same)
  List<Ball> balls = [];
  bool isAnimating = false;
  bool isAwaitingClick = false;
  bool isButtonDisabled = false;
  String buttonText = "Start Level";
  String instructions = "Click 'Start' to begin. Watch the yellow balls.";
  final Size gameCanvasSize = const Size(350, 450);
  int level = 1;
  int totalBalls = 3;
  int ballsToTrack = 1;
  double speed = 2.0;
  int foundTargets = 0;
  int _personalBest = 1;
  final Stopwatch _trackingStopwatch = Stopwatch();
  final Stopwatch _reactionStopwatch = Stopwatch();
  Duration? _trackedDuration;

  static const Color targetColor = Color(0xFFFFC107);
  static const Color defaultColor = Color(0xFF007BFF);
  static const Color correctColor = Color(0xFF28A745);
  static const Color incorrectColor = Color(0xFFDC3545);

  @override
  void initState() {
    super.initState();
    _controller =
        AnimationController(vsync: this, duration: const Duration(seconds: 1))
          ..addListener(() {
            if (isAnimating) {
              setState(() {
                for (var ball in balls) {
                  ball.update(gameCanvasSize);
                }
              });
            }
          });

    // Set the reference to this user's document in Firestore
    _userDocRef = FirebaseFirestore.instance
        .collection('users')
        .doc(widget.userId);

    _loadUserData();
  }

  // --- NEW: Sign Out Method ---
  Future<void> _signOut() async {
    await FirebaseAuth.instance.signOut();
    // No navigation needed. The StreamBuilder in BallTrackerApp will handle it.
  }

  Future<void> _loadUserData() async {
    try {
      // 1. Load the user's main document
      final userSnapshot = await _userDocRef.get();

      if (!userSnapshot.exists) {
        // This shouldn't happen if sign-up is correct, but good to check
        // We set a default 'User' name, which the logic below will fix
        // if an email is available from the auth/signup process.
        await _userDocRef.set({'personalBest': 1, 'displayName': 'User'});
      }

      final userData = userSnapshot.data() as Map<String, dynamic>?;

      // 2. Load the user's history from the subcollection
      final historySnapshot = await _userDocRef
          .collection('history')
          .orderBy('timestamp', descending: true) // Get most recent first
          .get();

      final history = historySnapshot.docs
          .map((doc) => LevelResult.fromJson(doc.data()))
          .toList();

      // --- START REPLACEMENT ---
      // This logic ensures the best possible username is displayed.
      String loadedName;
      final String? displayName = userData?['displayName'];
      final String? email = userData?['email']; // Get the stored email

      if (displayName != null &&
          displayName.isNotEmpty &&
          displayName != 'User') {
        // 1. Use displayName if it exists and is meaningful
        loadedName = displayName;
      } else if (email != null && email.isNotEmpty) {
        // 2. Fallback: create username from email
        loadedName = email.split('@').first;

        // Also, update the Firestore document for next time so we don't
        // have to do this every time the user logs in.
        // This check is important so we only write if needed.
        if (displayName == null ||
            displayName == 'User' ||
            displayName.isEmpty) {
          // We don't await this, just fire and forget. It's not critical.
          _userDocRef.update({'displayName': loadedName});
        }
      } else {
        // 3. Final fallback if email is also missing
        loadedName = 'User';
      }
      // --- END REPLACEMENT ---

      setState(() {
        _personalBest = userData?['personalBest'] ?? 1;
        _displayName = loadedName; // Load the determined name
        _userHistory = history;
      });
    } catch (e) {
      // Handle error (e.g., show a snackbar)
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Error loading user data: $e")));
    }
  }

  // --- MODIFIED: Saves to Firestore Subcollection ---
  Future<void> _saveUserHistory(LevelResult result) async {
    try {
      // We add the new result to the 'history' subcollection
      // We use the model's toJson() method, which now includes the timestamp
      await _userDocRef.collection('history').add(result.toJson());

      // Add to local list to update UI immediately
      setState(() {
        _userHistory.insert(
          0,
          result,
        ); // Add to beginning (since we sort descending)
      });
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Error saving history: $e")));
    }
  }

  // --- MODIFIED: Saves to Firestore Document ---
  Future<void> _savePersonalBest() async {
    if (level > _personalBest) {
      try {
        // Update the 'personalBest' field in the user's document
        await _userDocRef.update({'personalBest': level});
        setState(() {
          _personalBest = level;
        });
      } catch (e) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error saving personal best: $e")),
        );
      }
    }
  }

  // --- MODIFIED: Uses Firestore data ---
  Future<void> _exportHistoryToCsv() async {
    if (_userHistory.isEmpty) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text("No history to export.")));
      return;
    }

    final List<String> rowHeader = ['Level', 'Result', 'Time (s)', 'Timestamp'];
    List<List<String>> rows = [];
    rows.add(rowHeader);

    // _userHistory is already loaded from Firestore
    for (final result in _userHistory) {
      final List<String> row = [
        result.level.toString(),
        result.wasCompleted ? 'Answered' : 'Gave Up',
        result.time.toStringAsFixed(2),
        result.timestamp.toDate().toIso8601String(), // Add timestamp
      ];
      rows.add(row);
    }

    String csvData = rows.map((row) => row.join(',')).join('\n');

    final directory = await getTemporaryDirectory();
    // Use the Firebase UID for a unique filename
    final path = '${directory.path}/tracking_history_${widget.userId}.csv';
    final file = File(path);
    await file.writeAsString(csvData);

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text("CSV file created. Opening share dialog...")),
    );

    await Share.shareXFiles([
      XFile(path),
    ], subject: 'Ball Tracking History for User ${widget.userId}');
  }

  // (Game logic methods: _setupLevel, _startAnimation, _handleTap,
  // _handleSpaceBarPress, _increaseDifficulty, _resetLevel, _revealTargets
  // are almost identical, just the _saveUserHistory call is modified)

  // ... (setup, startAnimation, etc. are the same) ...

  void _setupLevel() {
    setState(() {
      instructions = "Watch the ${ballsToTrack} yellow ball(s).";
      isButtonDisabled = true;
      isAwaitingClick = false;
      isAnimating = false;
      foundTargets = 0;
      _trackedDuration = null;
      _reactionStopwatch.reset();
      balls.clear();

      final random = Random();
      for (int i = 0; i < totalBalls; i++) {
        const radius = 15.0;
        final x =
            radius + random.nextDouble() * (gameCanvasSize.width - 2 * radius);
        final y =
            radius + random.nextDouble() * (gameCanvasSize.height - 2 * radius);
        final angle = random.nextDouble() * 2 * pi;
        final dx = cos(angle) * speed;
        final dy = sin(angle) * speed;
        final isTarget = i < ballsToTrack;
        final color = isTarget ? targetColor : defaultColor;

        balls.add(
          Ball(
            position: Offset(x, y),
            velocity: Offset(dx, dy),
            color: color,
            isTarget: isTarget,
          ),
        );
      }
    });

    Future.delayed(const Duration(milliseconds: 2500), () {
      if (!mounted) return;
      setState(() {
        for (var ball in balls) {
          ball.color = defaultColor;
        }
        instructions = 'Tracking... (Press SPACE if you lose track)';
      });
      _startAnimation();
    });
  }

  void _startAnimation() {
    isAnimating = true;
    _trackingStopwatch.reset();
    _trackingStopwatch.start();
    _controller.repeat();

    Future.delayed(const Duration(seconds: 6), () {
      if (!isAnimating || !mounted) return;
      _trackingStopwatch.stop();
      isAnimating = false;
      _controller.stop();

      _reactionStopwatch.reset();
      _reactionStopwatch.start();

      setState(() {
        isAwaitingClick = true;
        instructions =
            "Click the ${ballsToTrack - foundTargets} ball(s) you were tracking.";
      });
    });
  }

  void _handleTap(Offset tapPosition) {
    if (!isAwaitingClick) return;
    for (final ball in balls) {
      final distance = (tapPosition - ball.position).distance;
      if (distance < ball.radius) {
        if (ball.color == correctColor || ball.color == incorrectColor)
          continue;
        setState(() {
          if (ball.isTarget) {
            ball.color = correctColor;
            foundTargets++;
            if (foundTargets == ballsToTrack) {
              _reactionStopwatch.stop();
              double reactionTimeInSeconds =
                  _reactionStopwatch.elapsedMilliseconds / 1000.0;

              instructions = "Correct! Well done! 🎉";
              isAwaitingClick = false;
              isButtonDisabled = false;
              buttonText = "Next Level";

              // --- MODIFIED: Save new data on SUCCESS ---
              final result = LevelResult(
                level: level,
                time: reactionTimeInSeconds,
                wasCompleted: true,
                timestamp: Timestamp.now(),
                gaveUp: false,
                wasIncorrect: false,
                targetsInLevel: ballsToTrack,
                targetsFound: foundTargets, // Will equal targetsInLevel
              );
              _saveUserHistory(result);
              _increaseDifficulty();
            } else {
              instructions =
                  "Good job! Find the remaining ${ballsToTrack - foundTargets} ball(s).";
            }
          } else {
            // --- USER CLICKED THE WRONG BALL ---
            ball.color = incorrectColor;
            instructions = "Incorrect. Try this level again. 🤔";
            isAwaitingClick = false;
            _reactionStopwatch.stop();

            // --- ADDED: Save new data on INCORRECT ---
            double reactionTimeInSeconds =
                _reactionStopwatch.elapsedMilliseconds / 1000.0;

            final result = LevelResult(
              level: level,
              time: reactionTimeInSeconds, // Time until wrong click
              wasCompleted: false,
              timestamp: Timestamp.now(),
              gaveUp: false,
              wasIncorrect: true, // This is the key
              targetsInLevel: ballsToTrack,
              targetsFound:
                  foundTargets, // How many they got before the mistake
            );
            _saveUserHistory(result);
            // --- END ADDED SECTION ---

            _revealTargets();
            _resetLevel();
          }
        });
        break;
      }
    }
  }

  void _handleSpaceBarPress() {
    if (!isAnimating) return;
    _trackingStopwatch.stop();
    _controller.stop();
    isAnimating = false;
    isAwaitingClick = false;

    setState(() {
      _trackedDuration = _trackingStopwatch.elapsed;
      double timeInSeconds = _trackedDuration!.inMilliseconds / 1000.0;

      // --- MODIFIED: Save new data on GIVE UP ---
      final result = LevelResult(
        level: level,
        time: timeInSeconds, // This is the tracking time
        wasCompleted: false,
        timestamp: Timestamp.now(),
        gaveUp: true, // This is the key
        wasIncorrect: false,
        targetsInLevel: ballsToTrack,
        targetsFound: 0, // They gave up before the clicking phase
      );
      _saveUserHistory(result);

      String formattedTime = timeInSeconds.toStringAsFixed(1);
      instructions = 'Tracked for ${formattedTime}s. Let\'s see the answer.';
      _revealTargets();
      _resetLevel();
    });
  }

  void _increaseDifficulty() {
    level++;
    _savePersonalBest(); // This will save to Firestore
    if (level % 2 == 0 && ballsToTrack < 5) {
      ballsToTrack++;
    }
    totalBalls++;
    if (level % 3 == 0) {
      speed += 0.25;
    }
  }

  void _resetLevel() {
    setState(() {
      isButtonDisabled = false;
      buttonText = "Try Again";
    });
  }

  void _revealTargets() {
    setState(() {
      for (final ball in balls) {
        if (ball.isTarget) {
          ball.color = targetColor;
        }
      }
    });
  }

  // --- NEW: Navigation to Brain Coach ---
  void _navigateToBrainCoach() {
    // We pass the most recent 20 sessions to avoid overloading the prompt
    // and to focus on *recent* performance.
    final recentHistory = _userHistory.take(20).toList();

    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => BrainCoachPage(
          userId: widget.userId,
          personalBest: _personalBest,
          recentHistory: recentHistory,
        ),
      ),
    );
  }
  // --- END NEW ---

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Focus(
      autofocus: true,
      onKeyEvent: (node, event) {
        if (event is KeyDownEvent &&
            event.logicalKey == LogicalKeyboardKey.space) {
          _handleSpaceBarPress();
          return KeyEventResult.handled;
        }
        return KeyEventResult.ignored;
      },
      child: Scaffold(
        // --- MODIFIED: AppBar with Sign Out Button AND Coach Button ---
        appBar: AppBar(
          title: Text('Ball Tracker 🧠 (User: $_displayName)'),
          backgroundColor: Colors.white,
          elevation: 1,
          actions: [
            // --- NEW BRAIN COACH BUTTON ---
            IconButton(
              icon: const Icon(Icons.psychology_outlined),
              tooltip: 'Brain Coach',
              onPressed: _navigateToBrainCoach,
            ),
            // --- END NEW BUTTON ---
            IconButton(
              icon: const Icon(Icons.logout),
              tooltip: 'Sign Out',
              onPressed: _signOut,
            ),
          ],
        ),
        // --- END MODIFIED APPBAR ---
        body: Center(
          child: SingleChildScrollView(
            child: Container(
              padding: const EdgeInsets.all(24.0),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  // --- Title is now in the AppBar ---
                  // const SizedBox(height: 20),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Level: $level',
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      Text(
                        'Personal Best: $_personalBest',
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w500,
                          color: Colors.black54,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 10),
                  Text(
                    "Level History",
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      color: Colors.grey.shade700,
                    ),
                  ),
                  Container(
                    height: 100,
                    margin: const EdgeInsets.symmetric(vertical: 8),
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.grey.shade300),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: ListView.builder(
                      // Use the local _userHistory list, which is loaded from Firestore
                      itemCount: _userHistory.length,
                      itemBuilder: (context, index) {
                        final result = _userHistory[index]; // Already sorted
                        final String resultText = result.wasCompleted
                            ? "Answered in ${result.time.toStringAsFixed(1)}s"
                            : "Gave up at ${result.time.toStringAsFixed(1)}s";

                        return Padding(
                          padding: const EdgeInsets.symmetric(
                            horizontal: 8.0,
                            vertical: 2.0,
                          ),
                          child: Text(
                            'Level ${result.level}: $resultText',
                            style: TextStyle(
                              color: result.wasCompleted
                                  ? Colors.green.shade700
                                  : Colors.red.shade700,
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(vertical: 8.0),
                    child: Text(
                      instructions,
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.bold,
                        color:
                            instructions.contains("Incorrect") ||
                                instructions.contains("Tracked for")
                            ? Colors.red
                            : const Color.fromARGB(255, 34, 34, 34),
                      ),
                    ),
                  ),
                  GestureDetector(
                    onTapDown: (details) => _handleTap(details.localPosition),
                    child: Container(
                      width: gameCanvasSize.width,
                      height: gameCanvasSize.height,
                      decoration: BoxDecoration(
                        border: Border.all(
                          color: Colors.grey.shade300,
                          width: 2,
                        ),
                        borderRadius: BorderRadius.circular(8.0),
                        color: const Color(0xFFF8F9FA),
                      ),
                      child: CustomPaint(
                        painter: BallPainter(balls: balls),
                        size: gameCanvasSize,
                      ),
                    ),
                  ),
                  const SizedBox(height: 20),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      ElevatedButton(
                        onPressed: isButtonDisabled ? null : _setupLevel,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF007BFF),
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(
                            horizontal: 25,
                            vertical: 12,
                          ),
                          textStyle: const TextStyle(fontSize: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(6.0),
                          ),
                        ),
                        child: Text(buttonText),
                      ),
                      const SizedBox(width: 10),
                      ElevatedButton.icon(
                        icon: const Icon(Icons.download),
                        label: const Text("Export CSV"),
                        onPressed: _exportHistoryToCsv,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.teal,
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(
                            horizontal: 25,
                            vertical: 12,
                          ),
                          textStyle: const TextStyle(fontSize: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(6.0),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// (BallPainter class remains exactly the same)
class BallPainter extends CustomPainter {
  final List<Ball> balls;
  BallPainter({required this.balls});

  @override
  void paint(Canvas canvas, Size size) {
    for (var ball in balls) {
      ball.draw(canvas);
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => true;
}

// --- NEW WIDGET: BRAIN COACH PAGE (RAG IMPLEMENTATION) ---

class BrainCoachPage extends StatefulWidget {
  final String userId;
  final int personalBest;
  final List<LevelResult> recentHistory;

  const BrainCoachPage({
    super.key,
    required this.userId,
    required this.personalBest,
    required this.recentHistory,
  });

  @override
  State<BrainCoachPage> createState() => _BrainCoachPageState();
}

class _BrainCoachPageState extends State<BrainCoachPage> {
  // Questionnaire State
  String _selectedGoal =
      'Improve my accuracy (click the right balls)'; // <--- THIS IS THE FIX
  String _selectedTime = '10-15 minute sessions';
  String _selectedIntensity = 'Focused and challenging';
  // RAG State
  bool _isLoading = false;
  String? _generatedPlan;
  String? _errorMessage;

  // --- RAG (Part C: Expert Knowledge Base) ---
  final Map<String, String> _expertKnowledgeBase = {
    'GENERAL_CONSISTENCY':
        "Consistency is key. Recommend a schedule of 3-5 sessions per week.",
    'REST_DAYS':
        "Cognitive rest is vital. Ensure the user has at least 2-3 rest days to consolidate learning.",
    'HIGH_INACCURACY':
        "User struggles with accuracy (high 'wasIncorrect' rate). Recommend focusing on *fewer* targets or lowering speed to build precision.",
    'HIGH_GIVE_UP':
        "User gives up often (high 'gaveUp' rate). This suggests the difficulty jump is too high. Recommend shorter sessions or staying at the current level to build confidence.",
    'NEARING_PERSONAL_BEST':
        "User is at or near their personal best. Encourage them, but also advise against burnout. Suggest a 'push' day followed by a rest day.",
    'STUCK_ON_LEVEL':
        "User seems to be stuck on a specific level. Recommend a 'scaffolding' approach: play the level *below* it twice successfully, then attempt the stuck level.",
    'NEW_USER':
        "User has very little history. Focus on building a consistent habit and exploring the game, not on high performance.",
  };

  // --- RAG (Part A: Summarize Performance) ---
  Map<String, dynamic> _summarizePerformance() {
    if (widget.recentHistory.isEmpty) {
      return {'personalBest': widget.personalBest, 'status': 'New User'};
    }

    int giveUpCount = 0;
    int incorrectCount = 0;
    Map<int, int> levelAttempts = {};
    int recentMaxLevel = 0;

    for (final session in widget.recentHistory) {
      if (session.gaveUp) giveUpCount++;
      if (session.wasIncorrect) incorrectCount++;
      levelAttempts[session.level] = (levelAttempts[session.level] ?? 0) + 1;
      if (session.level > recentMaxLevel) {
        recentMaxLevel = session.level;
      }
    }

    String failureMode = 'none';
    if (giveUpCount > incorrectCount && giveUpCount > 3) {
      failureMode = 'gaveUp';
    } else if (incorrectCount > giveUpCount && incorrectCount > 3) {
      failureMode = 'wasIncorrect';
    }

    int stuckOnLevel = 0;
    for (final entry in levelAttempts.entries) {
      final level = entry.key;
      final attempts = entry.value;
      final hasCompleted = widget.recentHistory.any(
        (s) => s.level == level && s.wasCompleted,
      );
      if (!hasCompleted && attempts >= 3) {
        if (level > stuckOnLevel) stuckOnLevel = level;
      }
    }

    return {
      'personalBest': widget.personalBest,
      'recentSessionCount': widget.recentHistory.length,
      'recentMaxLevel': recentMaxLevel,
      'primaryFailureMode': failureMode,
      'stuckOnLevel': stuckOnLevel > 0 ? stuckOnLevel : 'none',
    };
  }

  // --- RAG (Augment & Generate) ---
  Future<void> _runRagPipeline() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
      _generatedPlan = null;
    });

    try {
      // 1. RETRIEVE (Part A: Performance Summary)
      final performanceSummary = _summarizePerformance();
      final performanceJson = jsonEncode(performanceSummary);

      // 2. RETRIEVE (Part B: User Goals)
      final userGoals = {
        'mainGoal': _selectedGoal,
        'timeCommitment': _selectedTime,
        'intensity': _selectedIntensity,
      };
      final goalsJson = jsonEncode(userGoals);

      // 3. RETRIEVE (Part C: Knowledge Base)
      // This is simplified for the prompt. A real app might select rules dynamically.
      final knowledgeJson = jsonEncode(_expertKnowledgeBase);

      // 4. AUGMENT (Build the Prompt)
      final systemPrompt =
          """
You are an expert cognitive coach and brain training specialist. Your goal is to create a specific, encouraging, and actionable 7-day workout plan.

You will be given three pieces of information:
1.  **Performance Summary**: A JSON object of the user's recent game performance.
2.  **User Goals**: A JSON object of what the user wants to achieve.
3.  **Expert Rules**: A JSON object of training principles you must follow.

Your Task:
Create a personalized 7-day plan (e.g., "Day 1:", "Day 2:").
- Be encouraging and optimistic.
- Explain *why* you are recommending specific actions, referencing both their goals and their performance (e.g., "Since you want to improve accuracy and you've been clicking the wrong ball, we will focus on...").
- Be specific (e.g., "Play 3 games at Level ${performanceSummary['stuckOnLevel'] ?? 10}", "Try to beat your time on Level 8", "Today is a rest day.").
- Format the output as Markdown.
""";

      final userPrompt =
          """
Here is my data:

**1. My Performance Summary:**
$performanceJson

**2. My Goals:**
$goalsJson

**3. Expert Rules to Follow:**
$knowledgeJson

Please generate my 7-day personalized brain workout plan.
""";

      // 5. GENERATE (Call Gemini API)
      const apiKey =
          "AIzaSyDR0YSL7CPuZdp2M_8ZowmPpJ7mNjdvdMU"; // Handled by environment
      const apiUrl =
          'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=$apiKey';

      final response = await http.post(
        Uri.parse(apiUrl),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          'contents': [
            {
              'parts': [
                {'text': userPrompt},
              ],
            },
          ],
          'systemInstruction': {
            'parts': [
              {'text': systemPrompt},
            ],
          },
        }),
      );

      if (response.statusCode == 200) {
        final body = jsonDecode(response.body);
        final text = body['candidates'][0]['content']['parts'][0]['text'];
        setState(() {
          _generatedPlan = text;
        });
      } else {
        throw Exception('API Error (${response.statusCode}): ${response.body}');
      }
    } catch (e) {
      setState(() {
        _errorMessage = "Failed to generate plan: ${e.toString()}";
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Your Brain Coach')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "Tell me about your goals",
              style: Theme.of(context).textTheme.titleLarge,
            ),
            const SizedBox(height: 16),

            // --- Questionnaire ---
            _buildDropdown(
              label: 'My main goal is...',
              value: _selectedGoal,
              items: [
                'Improve my accuracy (click the right balls)',
                'Improve my endurance (track for longer)',
                'Improve my reaction speed (click faster)',
                'Beat my personal best score',
              ],
              onChanged: (val) => setState(() => _selectedGoal = val!),
            ),
            _buildDropdown(
              label: 'I want to have...',
              value: _selectedTime,
              items: [
                'Quick 5-minute sessions',
                '10-15 minute sessions',
                'Intense 20+ minute sessions',
              ],
              onChanged: (val) => setState(() => _selectedTime = val!),
            ),
            _buildDropdown(
              label: 'My training style is...',
              value: _selectedIntensity,
              items: [
                'Relaxed and just for fun',
                'Focused and challenging',
                'Intense and competitive',
              ],
              onChanged: (val) => setState(() => _selectedIntensity = val!),
            ),
            const SizedBox(height: 24),

            // --- Generate Button ---
            if (!_isLoading)
              ElevatedButton.icon(
                icon: const Icon(Icons.psychology),
                label: const Text('Generate My 7-Day Plan'),
                style: ElevatedButton.styleFrom(
                  minimumSize: const Size(double.infinity, 50),
                ),
                onPressed: _runRagPipeline,
              ),

            // --- Loading Indicator ---
            if (_isLoading) const Center(child: CircularProgressIndicator()),

            // --- Error Message ---
            if (_errorMessage != null)
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                child: Text(
                  _errorMessage!,
                  style: const TextStyle(color: Colors.red),
                ),
              ),

            // --- Result ---
            if (_generatedPlan != null)
              Container(
                margin: const EdgeInsets.only(top: 24.0),
                padding: const EdgeInsets.all(16.0),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(8.0),
                  border: Border.all(color: Colors.grey.shade300),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      "Your Personalized Plan",
                      style: Theme.of(context).textTheme.titleLarge,
                    ),
                    const Divider(height: 24),
                    // Use Markdown to render the LLM's response
                    MarkdownBody(data: _generatedPlan!, selectable: true),
                  ],
                ),
              ),
          ],
        ),
      ),
    );
  }

  // Helper widget for a clean dropdown
  Widget _buildDropdown({
    required String label,
    required String value,
    required List<String> items,
    required ValueChanged<String?> onChanged,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label, style: const TextStyle(fontWeight: FontWeight.w500)),
          const SizedBox(height: 8),
          DropdownButtonFormField<String>(
            value: value,
            isExpanded: true,
            items: items.map((String item) {
              return DropdownMenuItem<String>(
                value: item,
                child: Text(item, overflow: TextOverflow.ellipsis),
              );
            }).toList(),
            onChanged: onChanged,
            decoration: const InputDecoration(
              border: OutlineInputBorder(),
              contentPadding: EdgeInsets.symmetric(horizontal: 12.0),
            ),
          ),
        ],
      ),
    );
  }
}
